hydra:
  run:
    dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}_${model.tokenizer}_${datasets.name}_dim${model.mel_spec.n_mel_channels}_${datasets.latent_frames}hz_lr${optim.learning_rate}_bsz${datasets.batch_size_per_gpu}_dropout${model.arch.dropout}_ll_sm_attn_proj_align_vae_hubert23/${now:%Y-%m-%d}/${now:%H-%M-%S}

ckpts:
  logger: wandb  # wandb | tensorboard | null
  log_samples: False  # infer random sample per save checkpoint. wip, normal to fail with extra long samples
  save_per_updates: 50000  # save checkpoint per updates
  keep_last_n_checkpoints: -1  # -1 to keep all, 0 to not save intermediate, > 0 to keep last N checkpoints
  last_per_updates: 5000  # save last checkpoint per updates
  save_dir: ckpts/${model.name}_${model.mel_spec.mel_spec_type}_${model.tokenizer}_${datasets.name}_dim${model.mel_spec.n_mel_channels}_${datasets.latent_frames}hz_lr${optim.learning_rate}_bsz${datasets.batch_size_per_gpu}_dropout${model.arch.dropout}_ll_sm_attn_proj_align_vae_hubert23


datasets:
  name: LibriTTS_100_360_500
  batch_size_per_gpu: 51200  # 8 GPUs, 8 * 38400 = 307200
  batch_size_type: frame  # frame | sample
  max_samples: 64  # max sequences per batch if use frame-wise batch_size. we set 32 for small models, 64 for base models
  num_workers: 16
  latent_dataset_root: /vepfs/user/tts/speech/LibriTTS/
  latent_frames: 40
  latent_path: /root/code/descript-audio-codec/ldm_features/16khz_40hz_5544_kl1e-4_vae64_7khr_bigvgan_base_ll_sm_attn_proj_hubert23_align_vae/LibriTTS/

optim:
  epochs: 686  # only suitable for Emilia, if you want to train it on LibriTTS, set epoch 686
  learning_rate: 1e-4
  num_warmup_updates: 20000  # warmup updates
  grad_accumulation_steps: 1  # note: updates = steps / grad_accumulation_steps
  max_grad_norm: 1.0  # gradient clipping
  bnb_optimizer: False  # use bnb 8bit AdamW optimizer or not

model:
  name: F5TTS_v1_Small
  tokenizer: char
  tokenizer_path: null  # if 'custom' tokenizer, define the path want to use (should be vocab.txt)
  backbone: DiT
  arch:
    dim: 768
    depth: 18
    heads: 12
    ff_mult: 2
    text_dim: 512
    text_mask_padding: True
    conv_layers: 4
    pe_attn_head: null
    dropout: 0.0
    checkpoint_activations: False  # recompute activations and save memory for extra compute
  mel_spec:
    target_sample_rate: 16000
    n_mel_channels: 64
    hop_length: 400
    win_length: 1024
    n_fft: 1024
    mel_spec_type: latent  # vocos | bigvgan
  vocoder:
    is_local: False  # use local offline ckpt or not
    local_path: null  # local vocoder path
    # wandb: offline-run-20250510_083425-q16cddlx